-- Generated contact quality cleanup for suspicious_contact false positives.
-- Source: parser in functions/_dashboard-utils.js on 2026-07-05.
-- Bamboo Laundry (bamboo-laundry)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_ab488aaa9f379191', 'franchise_78ff31a2c34873b4', 'site_franchisee_id', 'phone', 'Telepon', '0813 2386 0556', '6281323860556', 'https://wa.me/6281323860556', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_e52d6e26c62db5f5', 'franchise_78ff31a2c34873b4', 'site_franchisee_id', 'phone', 'Telepon', '0812 8420 3032', '6281284203032', 'https://wa.me/6281284203032', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_78ff31a2c34873b4' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Black Kebab (black-kebab)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_90868833cfea8070', 'franchise_bb1c0ce2bb027a2f', 'site_franchisee_id', 'phone', 'Telepon', '0878 9000 0957', '6287890000957', 'https://wa.me/6287890000957', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_47628a9afbedb60d', 'franchise_bb1c0ce2bb027a2f', 'site_franchisee_id', 'phone', 'Telepon', '0817 4603 78', '62817460378', 'https://wa.me/62817460378', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_bb1c0ce2bb027a2f' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Clothes Laundry (clothes-laundry)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_f48de4d24c8f55e1', 'franchise_cf8a0c43aec9663d', 'site_franchisee_id', 'phone', 'Telepon', '0813 2386 0556', '6281323860556', 'https://wa.me/6281323860556', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_0c8ddfe5f33822b4', 'franchise_cf8a0c43aec9663d', 'site_franchisee_id', 'phone', 'Telepon', '0812 8420 3032', '6281284203032', 'https://wa.me/6281284203032', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_cf8a0c43aec9663d' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Diente De Leon Laundry (diente-de-leon-laundry)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_4745f2f37d2170dc', 'franchise_f84e116a7ad48664', 'site_franchisee_id', 'phone', 'Telepon', '0812 5888 6100', '6281258886100', 'https://wa.me/6281258886100', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_eecfdaf4e730f9af', 'franchise_f84e116a7ad48664', 'site_franchisee_id', 'phone', 'Telepon', '0878 2416 1519', '6287824161519', 'https://wa.me/6287824161519', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_f84e116a7ad48664' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- NYC PIZZA (nyc-pizza)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_33a814e1c7a0d69c', 'franchise_750d31f42a6bf6a4', 'site_franchisee_id', 'phone', 'Telepon', '0877 7549 7578', '6287775497578', 'https://wa.me/6287775497578', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_b075ab1c4e7ce913', 'franchise_750d31f42a6bf6a4', 'site_franchisee_id', 'phone', 'Telepon', '0813 9987 9788', '6281399879788', 'https://wa.me/6281399879788', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_750d31f42a6bf6a4' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Netto Laundromat (netto-laundromat)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_950c561766fda80c', 'franchise_881867b9bcc4da03', 'site_franchisee_id', 'phone', 'Telepon', '0818 0740 0770', '6281807400770', 'https://wa.me/6281807400770', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_6fee30ebac62f530', 'franchise_881867b9bcc4da03', 'site_franchisee_id', 'phone', 'Telepon', '0878 8666 4226', '6287886664226', 'https://wa.me/6287886664226', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_881867b9bcc4da03' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- dr. laundry (dr-laundry)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_7680c1af81f22f47', 'franchise_4ecf2e0cebf69e44', 'site_franchisee_id', 'phone', 'Telepon', '0851 8455 0162', '6285184550162', 'https://wa.me/6285184550162', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_85ad85f894531b31', 'franchise_4ecf2e0cebf69e44', 'site_franchisee_id', 'phone', 'Telepon', '0812 8441 5836', '6281284415836', 'https://wa.me/6281284415836', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_4ecf2e0cebf69e44' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Aloe Fresh (aloe-fresh)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_ad1d4714052a6ca4', 'franchise_cdd20ab5835b3f90', 'site_franchisee_id', 'phone', 'Kantor', '(021) 5930 3911 17', '62215930391117', 'tel:+62215930391117', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_de662bc167c843ef', 'franchise_cdd20ab5835b3f90', 'site_franchisee_id', 'phone', 'Kantor', '0819 3203 2101', '6281932032101', 'https://wa.me/6281932032101', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_cdd20ab5835b3f90' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Ayam Dadar Bandung (ayam-dadar-bandung)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_4639a6ebc973b214', 'franchise_9b1b422f75142561', 'site_franchisee_id', 'phone', 'Telepon', '0831 7464 3080', '6283174643080', 'https://wa.me/6283174643080', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_900155f7aaebb2b8', 'franchise_9b1b422f75142561', 'site_franchisee_id', 'phone', 'Telepon', '0857 8113 2540', '6285781132540', 'https://wa.me/6285781132540', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_8f9b1011ee9fa9c1', 'franchise_9b1b422f75142561', 'site_franchisee_id', 'phone', 'Telepon', '0852 9575 0621', '6285295750621', 'https://wa.me/6285295750621', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_71eef88b604d2942', 'franchise_9b1b422f75142561', 'site_franchisee_id', 'phone', 'Telepon', '0898 7036 407', '628987036407', 'https://wa.me/628987036407', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_9b1b422f75142561' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Coffeeland Indonesia (coffeeland-indonesia)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_2fe3e674c902bc2c', 'franchise_5bd4286dc4e3d250', 'site_franchisee_id', 'phone', 'Telepon', '0813 2235 6979', '6281322356979', 'https://wa.me/6281322356979', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_d9209f9a7ca40f73', 'franchise_5bd4286dc4e3d250', 'site_franchisee_id', 'phone', 'Telepon', '0878 2595 8155', '6287825958155', 'https://wa.me/6287825958155', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_5bd4286dc4e3d250' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- ES TEH LEGENDA (es-teh-legenda)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_ba4e257576c8eca8', 'franchise_324aeb6f7c904cb6', 'site_franchisee_id', 'phone', 'Telepon', '0813 9154 7539', '6281391547539', 'https://wa.me/6281391547539', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_1c38078da8df0fa1', 'franchise_324aeb6f7c904cb6', 'site_franchisee_id', 'phone', 'Telepon', '0813 9154 7528', '6281391547528', 'https://wa.me/6281391547528', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_324aeb6f7c904cb6' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Mangojack (mangojack)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_3647e26297673dfb', 'franchise_a56812531678041c', 'site_franchisee_id', 'phone', 'Telepon', '0822 2550 5500', '6282225505500', 'https://wa.me/6282225505500', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_c439b917b6b710ca', 'franchise_a56812531678041c', 'site_franchisee_id', 'phone', 'Telepon', '0822 1331 7007', '6282213317007', 'https://wa.me/6282213317007', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_a56812531678041c' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Masakan Mas Gawa (masakan-mas-gawa)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_ea4846e950a95084', 'franchise_03f65c9423f06d0b', 'site_franchisee_id', 'phone', 'Telepon', '0878 6405 6075', '6287864056075', 'https://wa.me/6287864056075', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_24a4b775130264f8', 'franchise_03f65c9423f06d0b', 'site_franchisee_id', 'phone', 'Telepon', '0818 0898 5548', '6281808985548', 'https://wa.me/6281808985548', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_03f65c9423f06d0b' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Nyam Yam! FWB (nyam-yam-fwb)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_5ea33adaa67c1767', 'franchise_fa07204903f63d8e', 'site_franchisee_id', 'phone', 'Telepon', '0878 0937 1485', '6287809371485', 'https://wa.me/6287809371485', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_e43f67eee633c124', 'franchise_fa07204903f63d8e', 'site_franchisee_id', 'phone', 'Telepon', '0878 0837 1485', '6287808371485', 'https://wa.me/6287808371485', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_fa07204903f63d8e' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Pempek Farina (pempek-farina)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_b9e7dba0178111c5', 'franchise_1636c6c40af34eb9', 'site_franchisee_id', 'phone', 'Telepon', '0812 3030 8247', '6281230308247', 'https://wa.me/6281230308247', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_f1b545774565ccfa', 'franchise_1636c6c40af34eb9', 'site_franchisee_id', 'phone', 'Telepon', '0811 3118 4010', '6281131184010', 'https://wa.me/6281131184010', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_1636c6c40af34eb9' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Qais Chicken (qais-chicken)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_4fd0d38061ffffd8', 'franchise_46df00821dd1b368', 'site_franchisee_id', 'phone', 'Telepon', '0853 9898 8191', '6285398988191', 'https://wa.me/6285398988191', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_e25996a851bbd63f', 'franchise_46df00821dd1b368', 'site_franchisee_id', 'phone', 'Telepon', '0856 9287 8550', '6285692878550', 'https://wa.me/6285692878550', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_46df00821dd1b368' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Si Tahu Giri (si-tahu-giri)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_198d7e09f0c8a32e', 'franchise_92869ee7b7a063e1', 'site_franchisee_id', 'phone', 'Telepon', '0857 2942 1739', '6285729421739', 'https://wa.me/6285729421739', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_f312e08442c1ae8a', 'franchise_92869ee7b7a063e1', 'site_franchisee_id', 'phone', 'Telepon', '0859 7488 3779', '6285974883779', 'https://wa.me/6285974883779', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_92869ee7b7a063e1' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Smokey Kebab (smokey-kebab)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_146bcbd6963acf15', 'franchise_a5dcf0ad303c5297', 'site_franchisee_id', 'phone', 'Telepon', '0812 1052 2358 0', '62812105223580', 'https://wa.me/62812105223580', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_a5dcf0ad303c5297' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Sunday Morning Express (sunday-morning-express)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_f391007903039b6f', 'franchise_05f9c81c2df1e35d', 'site_franchisee_id', 'phone', 'Telepon', '0823 2019 2014', '6282320192014', 'https://wa.me/6282320192014', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_05f9c81c2df1e35d' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Warminspi Rodjo (warminspi-rodjo)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_5c29e39c3fe81169', 'franchise_cde546057216efbf', 'site_franchisee_id', 'phone', 'Telepon', '0812 3430 0537', '6281234300537', 'https://wa.me/6281234300537', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_7485c68172c81b61', 'franchise_cde546057216efbf', 'site_franchisee_id', 'phone', 'Telepon', '0858 6714 3289', '6285867143289', 'https://wa.me/6285867143289', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_cde546057216efbf' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Bakmie cha-cha (bakmie-cha-cha)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_c2c40c08b409f7a3', 'franchise_69393ffe59d4227f', 'site_franchisee_id', 'phone', 'Telepon', '0823 2019 2014', '6282320192014', 'https://wa.me/6282320192014', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_69393ffe59d4227f' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Bakso Bakar Jarjozz (bakso-bakar-jarjozz)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_30f67940097efd36', 'franchise_f9ab0ad37df51d8e', 'site_franchisee_id', 'phone', 'Telepon', '(0274) 5018 156', '622745018156', 'tel:+622745018156', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_a2cf2d53e99d83f6', 'franchise_f9ab0ad37df51d8e', 'site_franchisee_id', 'phone', 'Telepon', '0857 2942 1739', '6285729421739', 'https://wa.me/6285729421739', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_f9ab0ad37df51d8e' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Bakso Benhil (bakso-benhil)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_5adfa4a4a375cef2', 'franchise_19d90d56caba48d4', 'site_franchisee_id', 'phone', 'Telepon', '0858 6839 7955', '6285868397955', 'https://wa.me/6285868397955', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_1a9b23c5cbc9f117', 'franchise_19d90d56caba48d4', 'site_franchisee_id', 'phone', 'Telepon', '0853 2661 1689', '6285326611689', 'https://wa.me/6285326611689', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_19d90d56caba48d4' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Baso Aci Akang (baso-aci-akang)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_e51e274ec94af63b', 'franchise_4d7fcd8b3d0e55bc', 'site_franchisee_id', 'phone', 'Telepon', '0812 8616 7838', '6281286167838', 'https://wa.me/6281286167838', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_b75de3d56dca0a46', 'franchise_4d7fcd8b3d0e55bc', 'site_franchisee_id', 'phone', 'Telepon', '0811 1210 0120', '6281112100120', 'https://wa.me/6281112100120', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_4d7fcd8b3d0e55bc' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- DOKAR (Donat Bakar) (dokar-donat-bakar)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_33d308fb4cc1b958', 'franchise_aa5e25088cf807fb', 'site_franchisee_id', 'phone', 'Telepon', '0815 5509 109', '628155509109', 'https://wa.me/628155509109', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_c0ce2f7c5a7e1289', 'franchise_aa5e25088cf807fb', 'site_franchisee_id', 'phone', 'Telepon', '0813 3782 9120', '6281337829120', 'https://wa.me/6281337829120', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_aa5e25088cf807fb' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Dons Burger (dons-burger)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_3a15a644b758dedf', 'franchise_b06bdda9c56b0d12', 'site_franchisee_id', 'phone', 'Telepon', '(021) 8273 7914', '622182737914', 'tel:+622182737914', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_b06bdda9c56b0d12' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Geprek Bensu (geprek-bensu)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_d3129589c66fc424', 'franchise_aec6d6441e6a9558', 'site_franchisee_id', 'phone', 'Call Center', '1500 612', '1500612', 'tel:1500612', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_aec6d6441e6a9558' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Kala Coffee (kala-coffee)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_b8c214f7357a701f', 'franchise_b166fbf5f72d6beb', 'site_franchisee_id', 'phone', 'Telepon', '0823 3388 9978', '6282333889978', 'https://wa.me/6282333889978', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_b45c97a5984bf651', 'franchise_b166fbf5f72d6beb', 'site_franchisee_id', 'phone', 'Telepon', '0823 2404 9790', '6282324049790', 'https://wa.me/6282324049790', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_b166fbf5f72d6beb' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Mastercheese Pizza (mastercheese-pizza)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_83cd33c81a581e2b', 'franchise_dcfce7a63474a708', 'site_franchisee_id', 'phone', 'Telepon', '0817 0365 2788 0', '62817036527880', 'https://wa.me/62817036527880', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_dcfce7a63474a708' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Negiya Bowl (negiya-bowl)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_6d87caede2de5dcd', 'franchise_b54527af09d550a8', 'site_franchisee_id', 'phone', 'Telepon', '0821 1000 3799 0', '62821100037990', 'https://wa.me/62821100037990', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_b54527af09d550a8' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Nyoklat Klasik (nyoklat-klasik)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_d6d22723dac3861c', 'franchise_b1877d2e928504a3', 'site_franchisee_id', 'phone', 'Telepon', '0858 3548 9999', '6285835489999', 'https://wa.me/6285835489999', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_8aed0e77dd590ce5', 'franchise_b1877d2e928504a3', 'site_franchisee_id', 'phone', 'Telepon', '0852 0306 9999', '6285203069999', 'https://wa.me/6285203069999', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_b1877d2e928504a3' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Roti Joka (roti-joka)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_6092828648feacca', 'franchise_fb2cb2ab5bd58102', 'site_franchisee_id', 'phone', 'Telepon', '0857 1011 2698', '6285710112698', 'https://wa.me/6285710112698', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_64eb8b5b2803464e', 'franchise_fb2cb2ab5bd58102', 'site_franchisee_id', 'phone', 'Telepon', '0821 1339 0248', '6282113390248', 'https://wa.me/6282113390248', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_fb2cb2ab5bd58102' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Suga Boba Indonesia (suga-boba-indonesia)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_eb15e62fca238ea2', 'franchise_b76e77b9f1e37e34', 'site_franchisee_id', 'phone', 'Telepon', '0857 3530 0400', '6285735300400', 'https://wa.me/6285735300400', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_752e92cc0e93b6b7', 'franchise_b76e77b9f1e37e34', 'site_franchisee_id', 'phone', 'Telepon', '0819 9740 0300', '6281997400300', 'https://wa.me/6281997400300', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_b76e77b9f1e37e34' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Sumoden (sumoden)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_df7ef6d30d5b36fb', 'franchise_684f97af5a3d0ccc', 'site_franchisee_id', 'phone', 'Telepon', '0823 1485 2331', '6282314852331', 'https://wa.me/6282314852331', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_a89321d5a8ca71cd', 'franchise_684f97af5a3d0ccc', 'site_franchisee_id', 'phone', 'Telepon', '0823 3388 9978', '6282333889978', 'https://wa.me/6282333889978', 'phone', 'high', 'active', 0) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_684f97af5a3d0ccc' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- JNE Express (jne-express)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_ea986f198232e944', 'franchise_7109ac5e04e5c6e6', 'site_franchisee_id', 'phone', 'Telepon', '(021) 2927 8888', '622129278888', 'tel:+622129278888', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_7109ac5e04e5c6e6' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
-- Keding (keding)
INSERT INTO franchise_contacts (id, franchise_id, source_site_id, contact_type, label, value, normalized_value, url, source_field, confidence, status, is_primary) VALUES ('contact_fix_d896b44eafee79db', 'franchise_bec7d160f4d6ef7d', 'site_franchisee_id', 'phone', 'Telepon', '+886 972 940 831', '886972940831', 'https://wa.me/886972940831', 'phone', 'high', 'active', 1) ON CONFLICT(franchise_id, source_site_id, contact_type, normalized_value) DO UPDATE SET label = excluded.label, value = excluded.value, url = excluded.url, source_field = excluded.source_field, confidence = excluded.confidence, status = 'active', is_primary = excluded.is_primary, updated_at = CURRENT_TIMESTAMP;
UPDATE franchise_quality_checks SET status = 'resolved', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE franchise_id = 'franchise_bec7d160f4d6ef7d' AND site_id = 'site_franchisee_id' AND check_type = 'suspicious_contact' AND status = 'open';
