
SELECT
  k.id,
  k.asset_id,
  k.franchise_id,
  k.source_text,
  k.structured_data,
  f.brand_name,
  f.slug,
  f.year_established,
  f.city_origin,
  f.brand_country,
  f.outlet_type,
  f.target_market,
  f.location_requirement,
  f.min_area_sqm,
  f.min_staff_count,
  f.setup_duration_days,
  f.rent_cost_text,
  f.contract_duration_months,
  f.fee_license_idr,
  f.fee_capex_idr,
  f.fee_construction_idr,
  f.working_capital_idr,
  f.additional_cost_notes,
  f.total_investment_idr,
  f.min_investment_idr,
  f.max_investment_idr,
  f.estimated_bep_months,
  f.estimated_bep_min_months,
  f.estimated_bep_max_months,
  f.omzet_monthly_idr,
  f.omzet_monthly_min_idr,
  f.omzet_monthly_max_idr,
  f.hpp_percent,
  f.net_profit_percent,
  f.net_profit_monthly_min_idr,
  f.net_profit_monthly_max_idr,
  f.royalty_percent,
  f.royalty_basis,
  f.royalty_period,
  f.support_system,
  f.office_address,
  f.outlets_location
FROM franchise_asset_knowledge k
JOIN franchises f ON f.id = k.franchise_id
WHERE k.extraction_status = 'extracted'
  AND COALESCE(k.source_text, '') <> ''
ORDER BY k.updated_at DESC;
