import { writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  ImportFranchiseeRowSchema,
  ImportFranchisorRowSchema,
  ImportUnclaimedRowSchema,
} from "../src/lib/shared-schemas";
import {
  IMPORT_BATCH_ID,
  applyRemote,
  createStats,
  ensureDir,
  insert,
  intOrNull,
  isLikelyClaimBrandRow,
  legacySource,
  loadCsv,
  lowerOrNull,
  floatOrNull,
  maybePackage,
  moneyOrNull,
  normalizeHakiStatus,
  normalizeListingStatus,
  normalizeRoyaltyBasis,
  normalizeText,
  normalizeVerificationTier,
  publication,
  printStats,
  shortDescFrom,
  sqlRaw,
  stableId,
  textOrNull,
  uniqueSlug,
  update,
  type ImportStats,
  type SqlPlan,
} from "./import-csv-utils";

const ROOT_DIR = resolve(__dirname, "..");
const DEFAULT_OUTPUT = join(ROOT_DIR, ".context", "d1-import-franchise-data.sql");
const SITE_ID = "site_franchisee_id";

function main() {
  const options = parseArgs(process.argv.slice(2));
  const plan = buildImportPlan();

  printStats(plan);

  if (options.dryRun) {
    return;
  }

  const outputPath = resolve(ROOT_DIR, options.out || DEFAULT_OUTPUT);
  ensureDir(dirname(outputPath));
  writeFileSync(outputPath, plan.statements.join("\n") + "\n", "utf8");
  console.log(`\nGenerated SQL: ${outputPath}`);

  if (options.applyRemote) {
    applyRemote(outputPath, options.account);
  }
}

function parseArgs(args: string[]) {
  const options = {
    dryRun: false,
    applyRemote: false,
    account: "franchise-network",
    out: "",
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--dry-run") options.dryRun = true;
    else if (arg === "--apply-remote") options.applyRemote = true;
    else if (arg === "--account") options.account = args[++i] || options.account;
    else if (arg === "--out") options.out = args[++i] || "";
    else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

function printHelp() {
  console.log(`Usage:
  pnpm run import:csv:dry
  pnpm run import:csv:sql
  pnpm run import:csv:remote

Options:
  --dry-run              Parse and validate without writing SQL
  --out <path>           SQL output path
  --apply-remote         Apply generated SQL to remote franchise_db through cfman
  --account <alias>      cfman account alias, defaults to franchise-network
`);
}

function buildImportPlan(): SqlPlan {
  const stats = createStats();
  const warnings: string[] = [];
  const statements: string[] = [
    "-- Generated by scripts/import-csv-to-d1.ts",
    `-- Import batch: ${IMPORT_BATCH_ID}`,
    "PRAGMA foreign_keys = ON;",
    insert(
      "import_batches",
      {
        id: IMPORT_BATCH_ID,
        source_name: "csv directory snapshot",
        source_kind: "csv",
        source_site_id: SITE_ID,
        status: "running",
      },
      ["id"],
    ),
  ];

  const slugRegistry = new Set<string>();

  importFranchisors(statements, stats.FRANCHISOR, warnings, slugRegistry);
  importUnclaimed(statements, stats.UNCLAIMED, warnings, slugRegistry);
  importFranchisees(statements, stats.FRANCHISEE, warnings);

  const totals = Object.values(stats).reduce(
    (acc, item) => {
      acc.seen += item.seen;
      acc.inserted += item.inserted;
      acc.skipped += item.skipped;
      acc.invalid += item.invalid;
      return acc;
    },
    { seen: 0, inserted: 0, skipped: 0, invalid: 0 },
  );

  statements.push(
    update(
      "import_batches",
      {
        completed_at: sqlRaw("CURRENT_TIMESTAMP"),
        status: "completed",
        rows_seen: totals.seen,
        rows_inserted: totals.inserted,
        rows_skipped: totals.skipped,
      },
      { id: IMPORT_BATCH_ID },
    ),
  );

  return { statements, stats, warnings };
}

function importFranchisors(
  statements: string[],
  stats: ImportStats,
  warnings: string[],
  slugRegistry: Set<string>,
) {
  const rows = loadCsv("franchisors.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportFranchisorRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`FRANCHISOR row ${index + 2}: missing brand_name`);
      return;
    }

    const row = parsed.data;
    const legacyId = row.id || stableId("franchisor_legacy", row.brand_name, String(index));
    const franchiseId = `franchise_${stableId("franchisor", legacyId, row.brand_name)}`;
    const profileId = `franchisor_profile_${stableId("franchisor_profile", legacyId, row.email_contact || row.whatsapp)}`;
    const slug = uniqueSlug(row.brand_name, slugRegistry, legacyId);
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchisor_profiles",
        {
          id: profileId,
          source_site_id: SITE_ID,
          company_name: textOrNull(row.company_name),
          pic_name: textOrNull(row.pic_name),
          email_contact: lowerOrNull(row.email_contact),
          country_code: textOrNull(row.country_code),
          whatsapp: textOrNull(row.whatsapp),
          website_url: textOrNull(row.website_url),
          instagram_url: textOrNull(row.instagram_url),
          facebook_url: textOrNull(row.facebook_url),
          tiktok_url: textOrNull(row.tiktok_url),
          youtube_url: textOrNull(row.youtube_url),
          linkedin_url: textOrNull(row.linkedin_url),
          nib_number: textOrNull(row.nib_number),
          haki_status: normalizeHakiStatus(row.haki_status),
          haki_number: textOrNull(row.haki_number),
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          raw_payload: payload,
        },
        ["id"],
      ),
      insert(
        "franchises",
        {
          id: franchiseId,
          franchisor_profile_id: profileId,
          source_site_id: SITE_ID,
          brand_name: normalizeText(row.brand_name),
          slug,
          category: textOrNull(row.category),
          status: normalizeListingStatus(row.status || "FREE"),
          verification_tier: normalizeVerificationTier(row.status || "FREE", row.is_verified),
          source_type: "csv_import",
          source_sheet: "FRANCHISOR",
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          year_established: intOrNull(row.year_established),
          city_origin: textOrNull(row.city_origin),
          outlet_type: textOrNull(row.outlet_type),
          location_requirement: textOrNull(row.location_requirement || row.location_size),
          rent_cost_text: textOrNull(row.rent_cost || row.rent_budget),
          contract_duration_months: intOrNull(row.contract_duration),
          fee_license_idr: moneyOrNull(row.fee_license),
          fee_capex_idr: moneyOrNull(row.fee_capex),
          fee_construction_idr: moneyOrNull(row.fee_construction),
          total_investment_idr: moneyOrNull(row.total_investment_value),
          min_investment_idr: moneyOrNull(row.total_investment_value),
          estimated_bep_months: intOrNull(row.estimated_bep_months),
          omzet_monthly_idr: moneyOrNull(row.omzet_monthly),
          hpp_percent: floatOrNull(row.hpp_percent),
          net_profit_percent: floatOrNull(row.net_profit_percent || row.profit_percent),
          royalty_percent: floatOrNull(row.royalty_percent),
          royalty_basis: normalizeRoyaltyBasis(row.royalty_basis),
          royalty_period: textOrNull(row.royalty_period),
          short_desc: textOrNull(row.short_desc),
          full_desc: textOrNull(row.full_desc),
          support_system: textOrNull(row.support_system || row.support),
          logo_url: textOrNull(row.logo_url),
          cover_url: textOrNull(row.cover_url),
          gallery_urls: textOrNull(row.gallery_urls),
          video_url: textOrNull(row.video_url),
          proposal_url: textOrNull(row.proposal_url),
          raw_payload: payload,
        },
        ["id"],
      ),
      maybePackage(franchiseId, row.brand_name, row.total_investment_value, "Initial investment package"),
      publication(franchiseId, SITE_ID, slug, true),
      legacySource("FRANCHISOR", legacyId, row.brand_name, "franchises", franchiseId, payload),
    );

    stats.inserted++;
  });
}

function importUnclaimed(
  statements: string[],
  stats: ImportStats,
  warnings: string[],
  slugRegistry: Set<string>,
) {
  const rows = loadCsv("unclaimed.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportUnclaimedRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`UNCLAIMED row ${index + 2}: missing brand_name`);
      return;
    }

    const row = parsed.data;
    if (!isLikelyClaimBrandRow(row)) {
      stats.skipped++;
      return;
    }

    const normalizedKey = normalizeText(row.id) || normalizeText(row.brand_name);
    const legacyId = row.id || stableId("unclaimed_legacy", normalizedKey, String(index));
    const franchiseId = `franchise_${stableId("unclaimed", legacyId, row.brand_name)}`;
    const slug = uniqueSlug(row.brand_name, slugRegistry, legacyId);
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchises",
        {
          id: franchiseId,
          source_site_id: SITE_ID,
          brand_name: normalizeText(row.brand_name),
          slug,
          category: textOrNull(row.category),
          subcategory: textOrNull(row.subcategory),
          label: textOrNull(row.label),
          status: "unclaimed",
          verification_tier: "unclaimed",
          source_type: "csv_import",
          source_sheet: "UNCLAIMED",
          legacy_row_id: legacyId,
          min_investment_idr: moneyOrNull(row.min_capital),
          max_investment_idr: moneyOrNull(row.max_capital),
          short_desc: textOrNull(shortDescFrom(row.full_desc)),
          full_desc: textOrNull(row.full_desc),
          phone: textOrNull(row.phone),
          office_address: textOrNull(row.office_address),
          outlets_location: textOrNull(row.outlets_location),
          proposal_url: textOrNull(row.brochures),
          raw_payload: payload,
        },
        ["id"],
      ),
      maybePackage(franchiseId, row.brand_name, row.min_capital, textOrNull(row.label) || "Public source package", row.max_capital),
      publication(franchiseId, SITE_ID, slug, false),
      legacySource("UNCLAIMED", legacyId, row.brand_name, "franchises", franchiseId, payload),
    );

    stats.inserted++;
  });
}

function importFranchisees(statements: string[], stats: ImportStats, warnings: string[]) {
  const rows = loadCsv("franchisee.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportFranchiseeRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`FRANCHISEE row ${index + 2}: missing name`);
      return;
    }

    const row = parsed.data;
    const legacyId = row.id || stableId("franchisee_legacy", row.email || row.whatsapp || row.name, String(index));
    const profileId = `franchisee_profile_${stableId("franchisee_profile", legacyId, row.email || row.whatsapp)}`;
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchisee_profiles",
        {
          id: profileId,
          source_site_id: SITE_ID,
          name: normalizeText(row.name),
          email: lowerOrNull(row.email),
          country_code: textOrNull(row.country_code),
          whatsapp: textOrNull(row.whatsapp),
          city_origin: textOrNull(row.city_origin || row.location),
          interest_category: textOrNull(row.interest_category || row.interest),
          budget_range: textOrNull(row.budget_range || row.budget),
          location_plan: textOrNull(row.location_plan),
          message: textOrNull(row.message),
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          raw_payload: payload,
        },
        ["id"],
      ),
      legacySource("FRANCHISEE", legacyId, row.email || row.whatsapp || row.name, "franchisee_profiles", profileId, payload),
    );

    stats.inserted++;
  });
}

main();
