import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  ImportFranchiseeRowSchema,
  ImportFranchisorRowSchema,
  ImportUnclaimedRowSchema,
  normalizeHakiStatusValue,
  normalizeListingStatusValue,
  normalizeRoyaltyBasisValue,
  normalizeVerificationTierValue,
} from "../src/lib/shared-schemas";

type CsvRow = Record<string, string>;
type ImportSource = "FRANCHISOR" | "FRANCHISEE" | "UNCLAIMED";

const ROOT_DIR = resolve(__dirname, "..");
const CSV_DIR = join(ROOT_DIR, "csv");
const DEFAULT_OUTPUT = join(ROOT_DIR, ".context", "d1-import-franchise-data.sql");
const SITE_ID = "site_franchisee_id";
const IMPORT_BATCH_ID = `import_csv_${csvSnapshotHash()}`;

interface ImportStats {
  seen: number;
  inserted: number;
  skipped: number;
  invalid: number;
}

interface SqlPlan {
  statements: string[];
  stats: Record<ImportSource, ImportStats>;
  warnings: string[];
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  const plan = buildImportPlan();

  printStats(plan);

  if (options.dryRun) {
    return;
  }

  const outputPath = resolve(ROOT_DIR, options.out || DEFAULT_OUTPUT);
  ensureDir(dirname(outputPath));
  writeFileSync(outputPath, plan.statements.join("\n") + "\n", "utf8");
  console.log(`\nGenerated SQL: ${outputPath}`);

  if (options.applyRemote) {
    applyRemote(outputPath, options.account);
  }
}

function parseArgs(args: string[]) {
  const options = {
    dryRun: false,
    applyRemote: false,
    account: "franchise-network",
    out: "",
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--dry-run") options.dryRun = true;
    else if (arg === "--apply-remote") options.applyRemote = true;
    else if (arg === "--account") options.account = args[++i] || options.account;
    else if (arg === "--out") options.out = args[++i] || "";
    else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

function printHelp() {
  console.log(`Usage:
  pnpm run import:csv:dry
  pnpm run import:csv:sql
  pnpm run import:csv:remote

Options:
  --dry-run              Parse and validate without writing SQL
  --out <path>           SQL output path
  --apply-remote         Apply generated SQL to remote franchise_db through cfman
  --account <alias>      cfman account alias, defaults to franchise-network
`);
}

function buildImportPlan(): SqlPlan {
  const stats = createStats();
  const warnings: string[] = [];
  const statements: string[] = [
    "-- Generated by scripts/import-csv-to-d1.ts",
    `-- Import batch: ${IMPORT_BATCH_ID}`,
    "PRAGMA foreign_keys = ON;",
    insert(
      "import_batches",
      {
        id: IMPORT_BATCH_ID,
        source_name: "csv directory snapshot",
        source_kind: "csv",
        source_site_id: SITE_ID,
        status: "running",
      },
      ["id"],
    ),
  ];

  const slugRegistry = new Set<string>();

  importFranchisors(statements, stats.FRANCHISOR, warnings, slugRegistry);
  importUnclaimed(statements, stats.UNCLAIMED, warnings, slugRegistry);
  importFranchisees(statements, stats.FRANCHISEE, warnings);

  const totals = Object.values(stats).reduce(
    (acc, item) => {
      acc.seen += item.seen;
      acc.inserted += item.inserted;
      acc.skipped += item.skipped;
      acc.invalid += item.invalid;
      return acc;
    },
    { seen: 0, inserted: 0, skipped: 0, invalid: 0 },
  );

  statements.push(
    update(
      "import_batches",
      {
        completed_at: sqlRaw("CURRENT_TIMESTAMP"),
        status: "completed",
        rows_seen: totals.seen,
        rows_inserted: totals.inserted,
        rows_skipped: totals.skipped,
      },
      { id: IMPORT_BATCH_ID },
    ),
  );

  return { statements, stats, warnings };
}

function importFranchisors(
  statements: string[],
  stats: ImportStats,
  warnings: string[],
  slugRegistry: Set<string>,
) {
  const rows = loadCsv("franchisors.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportFranchisorRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`FRANCHISOR row ${index + 2}: missing brand_name`);
      return;
    }

    const row = parsed.data;
    const legacyId = row.id || stableId("franchisor_legacy", row.brand_name, String(index));
    const franchiseId = `franchise_${stableId("franchisor", legacyId, row.brand_name)}`;
    const profileId = `franchisor_profile_${stableId("franchisor_profile", legacyId, row.email_contact || row.whatsapp)}`;
    const slug = uniqueSlug(row.brand_name, slugRegistry, legacyId);
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchisor_profiles",
        {
          id: profileId,
          source_site_id: SITE_ID,
          company_name: textOrNull(row.company_name),
          pic_name: textOrNull(row.pic_name),
          email_contact: lowerOrNull(row.email_contact),
          country_code: textOrNull(row.country_code),
          whatsapp: textOrNull(row.whatsapp),
          website_url: textOrNull(row.website_url),
          instagram_url: textOrNull(row.instagram_url),
          facebook_url: textOrNull(row.facebook_url),
          tiktok_url: textOrNull(row.tiktok_url),
          youtube_url: textOrNull(row.youtube_url),
          linkedin_url: textOrNull(row.linkedin_url),
          nib_number: textOrNull(row.nib_number),
          haki_status: normalizeHakiStatus(row.haki_status),
          haki_number: textOrNull(row.haki_number),
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          raw_payload: payload,
        },
        ["id"],
      ),
      insert(
        "franchises",
        {
          id: franchiseId,
          franchisor_profile_id: profileId,
          source_site_id: SITE_ID,
          brand_name: normalizeText(row.brand_name),
          slug,
          category: textOrNull(row.category),
          status: normalizeListingStatus(row.status || "FREE"),
          verification_tier: normalizeVerificationTier(row.status || "FREE", row.is_verified),
          source_type: "csv_import",
          source_sheet: "FRANCHISOR",
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          year_established: intOrNull(row.year_established),
          city_origin: textOrNull(row.city_origin),
          outlet_type: textOrNull(row.outlet_type),
          location_requirement: textOrNull(row.location_requirement || row.location_size),
          rent_cost_text: textOrNull(row.rent_cost || row.rent_budget),
          contract_duration_months: intOrNull(row.contract_duration),
          fee_license_idr: moneyOrNull(row.fee_license),
          fee_capex_idr: moneyOrNull(row.fee_capex),
          fee_construction_idr: moneyOrNull(row.fee_construction),
          total_investment_idr: moneyOrNull(row.total_investment_value),
          min_investment_idr: moneyOrNull(row.total_investment_value),
          estimated_bep_months: intOrNull(row.estimated_bep_months),
          omzet_monthly_idr: moneyOrNull(row.omzet_monthly),
          hpp_percent: floatOrNull(row.hpp_percent),
          net_profit_percent: floatOrNull(row.net_profit_percent || row.profit_percent),
          royalty_percent: floatOrNull(row.royalty_percent),
          royalty_basis: normalizeRoyaltyBasis(row.royalty_basis),
          royalty_period: textOrNull(row.royalty_period),
          short_desc: textOrNull(row.short_desc),
          full_desc: textOrNull(row.full_desc),
          support_system: textOrNull(row.support_system || row.support),
          logo_url: textOrNull(row.logo_url),
          cover_url: textOrNull(row.cover_url),
          gallery_urls: textOrNull(row.gallery_urls),
          video_url: textOrNull(row.video_url),
          proposal_url: textOrNull(row.proposal_url),
          raw_payload: payload,
        },
        ["id"],
      ),
      maybePackage(franchiseId, row.brand_name, row.total_investment_value, "Initial investment package"),
      publication(franchiseId, SITE_ID, slug, true),
      legacySource("FRANCHISOR", legacyId, row.brand_name, "franchises", franchiseId, payload),
    );

    stats.inserted++;
  });
}

function importUnclaimed(
  statements: string[],
  stats: ImportStats,
  warnings: string[],
  slugRegistry: Set<string>,
) {
  const rows = loadCsv("unclaimed.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportUnclaimedRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`UNCLAIMED row ${index + 2}: missing brand_name`);
      return;
    }

    const row = parsed.data;
    if (!isLikelyClaimBrandRow(row)) {
      stats.skipped++;
      return;
    }

    const normalizedKey = normalizeText(row.id) || normalizeText(row.brand_name);
    const legacyId = row.id || stableId("unclaimed_legacy", normalizedKey, String(index));
    const franchiseId = `franchise_${stableId("unclaimed", legacyId, row.brand_name)}`;
    const slug = uniqueSlug(row.brand_name, slugRegistry, legacyId);
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchises",
        {
          id: franchiseId,
          source_site_id: SITE_ID,
          brand_name: normalizeText(row.brand_name),
          slug,
          category: textOrNull(row.category),
          subcategory: textOrNull(row.subcategory),
          label: textOrNull(row.label),
          status: "unclaimed",
          verification_tier: "unclaimed",
          source_type: "csv_import",
          source_sheet: "UNCLAIMED",
          legacy_row_id: legacyId,
          min_investment_idr: moneyOrNull(row.min_capital),
          max_investment_idr: moneyOrNull(row.max_capital),
          short_desc: textOrNull(shortDescFrom(row.full_desc)),
          full_desc: textOrNull(row.full_desc),
          phone: textOrNull(row.phone),
          office_address: textOrNull(row.office_address),
          outlets_location: textOrNull(row.outlets_location),
          proposal_url: textOrNull(row.brochures),
          raw_payload: payload,
        },
        ["id"],
      ),
      maybePackage(franchiseId, row.brand_name, row.min_capital, textOrNull(row.label) || "Public source package", row.max_capital),
      publication(franchiseId, SITE_ID, slug, false),
      legacySource("UNCLAIMED", legacyId, row.brand_name, "franchises", franchiseId, payload),
    );

    stats.inserted++;
  });
}

function importFranchisees(statements: string[], stats: ImportStats, warnings: string[]) {
  const rows = loadCsv("franchisee.csv");
  stats.seen = rows.length;

  rows.forEach((raw, index) => {
    const parsed = ImportFranchiseeRowSchema.safeParse(raw);
    if (!parsed.success) {
      stats.invalid++;
      warnings.push(`FRANCHISEE row ${index + 2}: missing name`);
      return;
    }

    const row = parsed.data;
    const legacyId = row.id || stableId("franchisee_legacy", row.email || row.whatsapp || row.name, String(index));
    const profileId = `franchisee_profile_${stableId("franchisee_profile", legacyId, row.email || row.whatsapp)}`;
    const payload = JSON.stringify(row);

    statements.push(
      insert(
        "franchisee_profiles",
        {
          id: profileId,
          source_site_id: SITE_ID,
          name: normalizeText(row.name),
          email: lowerOrNull(row.email),
          country_code: textOrNull(row.country_code),
          whatsapp: textOrNull(row.whatsapp),
          city_origin: textOrNull(row.city_origin || row.location),
          interest_category: textOrNull(row.interest_category || row.interest),
          budget_range: textOrNull(row.budget_range || row.budget),
          location_plan: textOrNull(row.location_plan),
          message: textOrNull(row.message),
          legacy_row_id: legacyId,
          legacy_timestamp: textOrNull(row.timestamp),
          raw_payload: payload,
        },
        ["id"],
      ),
      legacySource("FRANCHISEE", legacyId, row.email || row.whatsapp || row.name, "franchisee_profiles", profileId, payload),
    );

    stats.inserted++;
  });
}

function loadCsv(fileName: string): CsvRow[] {
  const filePath = join(CSV_DIR, fileName);
  if (!existsSync(filePath)) {
    throw new Error(`Missing CSV file: ${filePath}`);
  }

  const rows = parseCsvRows(readFileSync(filePath, "utf8"));
  if (rows.length < 2) return [];
  const headers = rows[0].map((header, index) => normalizeHeader(header, index));

  return rows
    .slice(1)
    .map((values) => {
      const item: CsvRow = {};
      headers.forEach((header, index) => {
        if (!header) return;
        item[header] = normalizeText(values[index] || "");
      });
      return item;
    })
    .filter((item) => Object.values(item).some(Boolean));
}

function parseCsvRows(content: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  const input = (content || "").replace(/^\uFEFF/, "");

  for (let i = 0; i < input.length; i++) {
    const ch = input[i];
    const next = input[i + 1];

    if (ch === "\"") {
      if (inQuotes && next === "\"") {
        field += "\"";
        i++;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (ch === "," && !inQuotes) {
      row.push(field);
      field = "";
      continue;
    }

    if ((ch === "\n" || ch === "\r") && !inQuotes) {
      if (ch === "\r" && next === "\n") i++;
      row.push(field);
      field = "";
      if (row.some((cell) => normalizeText(cell))) rows.push(row);
      row = [];
      continue;
    }

    field += ch;
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    if (row.some((cell) => normalizeText(cell))) rows.push(row);
  }

  return rows;
}

function normalizeHeader(header: string, index: number) {
  const normalized = normalizeText(header);
  if (normalized) return normalized;
  return `extra_${index + 1}`;
}

function insert(table: string, values: Record<string, SqlValue>, conflictColumns: string[] = []) {
  const columns = Object.keys(values);
  const sqlValues = columns.map((column) => sql(values[column]));
  const conflict = conflictColumns.length
    ? ` ON CONFLICT(${conflictColumns.join(", ")}) DO NOTHING`
    : "";
  return `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${sqlValues.join(", ")})${conflict};`;
}

function update(table: string, values: Record<string, SqlValue>, where: Record<string, SqlValue>) {
  const setClause = Object.entries(values)
    .map(([key, value]) => `${key} = ${sql(value)}`)
    .join(", ");
  const whereClause = Object.entries(where)
    .map(([key, value]) => `${key} = ${sql(value)}`)
    .join(" AND ");
  return `UPDATE ${table} SET ${setClause} WHERE ${whereClause};`;
}

type SqlValue = string | number | null | SqlRaw;

interface SqlRaw {
  raw: string;
}

function sqlRaw(raw: string): SqlRaw {
  return { raw };
}

function sql(value: SqlValue): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "object" && "raw" in value) return value.raw;
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function maybePackage(franchiseId: string, brandName: string, minValue?: string, label = "Investment package", maxValue?: string | null) {
  const min = moneyOrNull(minValue);
  const max = moneyOrNull(maxValue || "");
  if (!min && !max) return "-- package skipped: no price";

  const id = `package_${stableId(franchiseId, label)}`;
  return insert(
    "franchise_packages",
    {
      id,
      franchise_id: franchiseId,
      package_name: label,
      package_label: brandName,
      price_idr: min,
      min_capital_idr: min,
      max_capital_idr: max,
      description: label,
      display_order: 1,
    },
    ["id"],
  );
}

function publication(franchiseId: string, siteId: string, slug: string, isPrimary: boolean) {
  return insert(
    "franchise_site_publications",
    {
      id: `publication_${stableId(franchiseId, siteId)}`,
      franchise_id: franchiseId,
      site_id: siteId,
      slug,
      canonical_url: `https://franchisee.id/peluang-usaha/${slug}/`,
      publication_status: "published",
      is_primary: isPrimary ? 1 : 0,
      first_published_at: sqlRaw("CURRENT_TIMESTAMP"),
      last_synced_at: sqlRaw("CURRENT_TIMESTAMP"),
    },
    ["id"],
  );
}

function legacySource(
  source: ImportSource,
  legacyRowId: string,
  normalizedKeySeed: string,
  targetTable: string,
  targetId: string,
  payload: string,
) {
  const normalizedKey = normalizeKey(legacyRowId || normalizedKeySeed);
  return insert(
    "legacy_source_rows",
    {
      id: `legacy_${stableId(source, normalizedKey)}`,
      import_batch_id: IMPORT_BATCH_ID,
      source_sheet: source,
      legacy_row_id: textOrNull(legacyRowId),
      normalized_key: normalizedKey,
      target_table: targetTable,
      target_id: targetId,
      raw_payload: payload,
    },
    ["id"],
  );
}

function createStats(): Record<ImportSource, ImportStats> {
  return {
    FRANCHISOR: { seen: 0, inserted: 0, skipped: 0, invalid: 0 },
    FRANCHISEE: { seen: 0, inserted: 0, skipped: 0, invalid: 0 },
    UNCLAIMED: { seen: 0, inserted: 0, skipped: 0, invalid: 0 },
  };
}

function printStats(plan: SqlPlan) {
  console.log("CSV import plan:");
  for (const source of ["FRANCHISOR", "UNCLAIMED", "FRANCHISEE"] as ImportSource[]) {
    const item = plan.stats[source];
    console.log(
      `- ${source}: seen=${item.seen}, insert_statements=${item.inserted}, skipped=${item.skipped}, invalid=${item.invalid}`,
    );
  }
  if (plan.warnings.length) {
    console.log("\nWarnings:");
    plan.warnings.slice(0, 10).forEach((warning) => console.log(`- ${warning}`));
    if (plan.warnings.length > 10) console.log(`- ... ${plan.warnings.length - 10} more`);
  }
  console.log(`\nSQL statements: ${plan.statements.length}`);
}

function applyRemote(outputPath: string, account: string) {
  console.log(`\nApplying SQL to remote franchise_db with cfman account "${account}"...`);
  const result = spawnSync(
    "npx",
    ["cfman", "wrangler", "--account", account, "d1", "execute", "franchise_db", "--remote", "--file", outputPath],
    {
      cwd: ROOT_DIR,
      shell: process.platform === "win32",
      stdio: "inherit",
      env: {
        ...process.env,
        CLOUDFLARE_API_TOKEN: "",
      },
    },
  );

  if (result.status !== 0) {
    process.exit(result.status || 1);
  }
}

function ensureDir(path: string) {
  if (!existsSync(path)) mkdirSync(path, { recursive: true });
}

function stableId(...parts: string[]) {
  return createHash("sha1")
    .update(parts.map((part) => normalizeText(part)).join("|"))
    .digest("hex")
    .slice(0, 16);
}

function csvSnapshotHash() {
  const hash = createHash("sha1");
  for (const fileName of ["franchisors.csv", "unclaimed.csv", "franchisee.csv"]) {
    const filePath = join(CSV_DIR, fileName);
    hash.update(fileName);
    hash.update(existsSync(filePath) ? readFileSync(filePath) : "");
  }
  return hash.digest("hex").slice(0, 16);
}

function uniqueSlug(brandName: string, registry: Set<string>, legacyId: string) {
  const base = slugify(brandName) || `brand-${stableId(brandName, legacyId).slice(0, 8)}`;
  let slug = base;
  if (registry.has(slug)) slug = `${base}-${stableId(legacyId).slice(0, 6)}`;
  registry.add(slug);
  return slug;
}

function slugify(text: string) {
  return normalizeText(text)
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^\w-]+/g, "")
    .replace(/--+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");
}

function normalizeText(value?: string | null) {
  return (value || "").toString().replace(/\s+/g, " ").trim();
}

function normalizeKey(value: string) {
  return normalizeText(value).toLowerCase();
}

function textOrNull(value?: string | null) {
  const normalized = normalizeText(value);
  return normalized || null;
}

function lowerOrNull(value?: string | null) {
  const normalized = normalizeText(value).toLowerCase();
  return normalized || null;
}

function intOrNull(value?: string | null) {
  const digits = normalizeText(value).replace(/[^0-9-]/g, "");
  if (!digits) return null;
  const parsed = Number.parseInt(digits, 10);
  return Number.isFinite(parsed) ? parsed : null;
}

function floatOrNull(value?: string | null) {
  const normalized = normalizeText(value).replace(",", ".");
  if (!normalized) return null;
  const parsed = Number.parseFloat(normalized.replace(/[^0-9.-]/g, ""));
  return Number.isFinite(parsed) ? parsed : null;
}

function moneyOrNull(value?: string | null) {
  const normalized = normalizeText(value);
  if (!normalized) return null;
  const parsed = Number.parseInt(normalized.replace(/[^0-9]/g, ""), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

function normalizeListingStatus(value?: string | null) {
  return normalizeListingStatusValue(value);
}

function normalizeVerificationTier(status?: string | null, isVerified?: string | null) {
  return normalizeVerificationTierValue(status, isVerified);
}

function normalizeRoyaltyBasis(value?: string | null) {
  return normalizeRoyaltyBasisValue(value);
}

function normalizeHakiStatus(value?: string | null) {
  return normalizeHakiStatusValue(value);
}

function shortDescFrom(value?: string | null) {
  const normalized = normalizeText(value?.replace(/<[^>]*>?/gm, ""));
  if (!normalized) return null;
  return normalized.length > 120 ? `${normalized.slice(0, 117)}...` : normalized;
}

function isLikelyClaimBrandRow(item: CsvRow) {
  const brandName = normalizeText(item.brand_name);
  if (!brandName) return false;
  if (brandName.length < 2) return false;
  if (!/[a-z]/i.test(brandName)) return false;
  if (isUrlLike(brandName) || isPhoneLike(brandName)) return false;
  if (isLegalEntityLike(brandName) || isContactLabelLike(brandName) || isAddressLike(brandName)) return false;

  const hasEvidence =
    normalizeText(item.source_ignore) ||
    normalizeText(item.full_desc) ||
    normalizeText(item.company_name) ||
    normalizeText(item.phone) ||
    normalizeText(item.label);

  return Boolean(hasEvidence);
}

function isUrlLike(text: string) {
  return /^(https?:\/\/|www\.)/i.test(text);
}

function isPhoneLike(text: string) {
  const raw = normalizeText(text);
  const digits = raw.replace(/\D/g, "");
  return digits.length >= 9 && digits.length <= 16 && digits.length / Math.max(raw.length, 1) > 0.6;
}

function isLegalEntityLike(text: string) {
  return /^(pt|cv|ud|pd|yayasan|koperasi|perum|tbk)\b\.?/i.test(normalizeText(text));
}

function isContactLabelLike(text: string) {
  const raw = normalizeText(text).toLowerCase();
  if (!raw) return false;
  return /\b(call|telp|telepon|whatsapp|wa|marketing|owner|admin|contact|cp|ibu|bpk)\b/.test(raw);
}

function isAddressLike(text: string) {
  const raw = normalizeText(text).toLowerCase();
  if (!raw) return false;
  const hasAddressToken = /\b(jl|jalan|rt|rw|kel|kec|kab|kota|blok|no|nomor|ruko|komplek|km|desa|kav|kavling)\b/.test(raw);
  if (!hasAddressToken) return false;
  const hasDigits = /\d/.test(raw);
  const words = raw.split(/\s+/).filter(Boolean).length;
  return hasDigits || words >= 4;
}

main();
