import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { z } from "zod";
import { inferFranchiseLocations } from "../src/lib/franchise-location-normalization";
import { D1FranchiseRowSchema, type D1FranchiseRow } from "../src/lib/shared-schemas";

const ROOT_DIR = resolve(__dirname, "..");
const DEFAULT_INPUT = join(ROOT_DIR, "json", "d1-franchise-static-data.json");
const DEFAULT_OUTPUT = join(ROOT_DIR, ".context", "franchise-location-sync.sql");
const GENERATED_SOURCE_FIELDS = ["city_origin", "office_address", "outlets_location", "location_requirement"];

function main() {
  const options = parseArgs(process.argv.slice(2));
  const inputPath = resolve(ROOT_DIR, options.input || DEFAULT_INPUT);
  const outputPath = resolve(ROOT_DIR, options.out || DEFAULT_OUTPUT);
  const rows = loadRows(inputPath);
  const statements = buildSql(rows);

  ensureParent(outputPath);
  writeFileSync(outputPath, `${statements.join("\n")}\n`, "utf8");

  const locationCount = statements.filter((line) => line.startsWith("INSERT OR IGNORE INTO locations")).length;
  const relationCount = statements.filter((line) => line.startsWith("INSERT OR REPLACE INTO franchise_locations")).length;
  console.log("Franchise location sync:");
  console.log(`- input=${inputPath}`);
  console.log(`- franchises=${rows.length}`);
  console.log(`- locations=${locationCount}`);
  console.log(`- franchise_locations=${relationCount}`);
  console.log(`- output=${outputPath}`);

  if (options.applyRemote) applyRemote(outputPath, options.account);
}

function parseArgs(args: string[]) {
  const options = {
    input: "",
    out: "",
    applyRemote: false,
    account: "franchise-network",
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--input") options.input = args[++i] || "";
    else if (arg === "--out") options.out = args[++i] || "";
    else if (arg === "--apply-remote") options.applyRemote = true;
    else if (arg === "--account") options.account = args[++i] || options.account;
    else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

function printHelp() {
  console.log(`Usage:
  pnpm run locations:sync
  pnpm run locations:sync -- --apply-remote

Options:
  --input <path>        D1 static data JSON, defaults to json/d1-franchise-static-data.json
  --out <path>          SQL output path, defaults to .context/franchise-location-sync.sql
  --apply-remote        Apply generated SQL to remote franchise_db through cfman/wrangler
  --account <alias>     cfman account alias, defaults to franchise-network
`);
}

function loadRows(filePath: string): D1FranchiseRow[] {
  const parsed = JSON.parse(readFileSync(filePath, "utf8"));
  return z.array(D1FranchiseRowSchema).parse(parsed);
}

function buildSql(rows: D1FranchiseRow[]) {
  const statements = [
    "-- Generated by scripts/sync-franchise-locations.ts",
    "PRAGMA foreign_keys = ON;",
    deleteGeneratedRows(rows),
  ];
  const locationSlugs = new Set<string>();

  for (const row of rows) {
    for (const location of inferFranchiseLocations(row)) {
      const locationId = `location_${location.slug}`;
      if (!locationSlugs.has(location.slug)) {
        locationSlugs.add(location.slug);
        statements.push(
          `INSERT OR IGNORE INTO locations (id, country_code, province, city, slug) VALUES (${sql(locationId)}, 'ID', ${sql(location.province)}, ${sql(location.label)}, ${sql(location.slug)});`,
        );
      }

      const relationId = `franchise_location_${stableId(row.id, location.locationType, location.sourceField, location.slug)}`;
      statements.push(
        `INSERT OR REPLACE INTO franchise_locations (id, franchise_id, location_id, location_text, location_type, source_field, confidence_score) VALUES (${sql(relationId)}, ${sql(row.id)}, ${sql(locationId)}, ${sql(location.sourceText)}, ${sql(location.locationType)}, ${sql(location.sourceField)}, ${location.confidence.toFixed(2)});`,
      );
    }
  }

  return statements;
}

function deleteGeneratedRows(rows: D1FranchiseRow[]) {
  const ids = rows.map((row) => sql(row.id)).join(", ");
  const fields = GENERATED_SOURCE_FIELDS.map(sql).join(", ");
  return `DELETE FROM franchise_locations WHERE source_field IN (${fields}) AND franchise_id IN (${ids});`;
}

function applyRemote(filePath: string, account: string) {
  const result = spawnSync("npx", ["cfman", "wrangler", "--account", account, "d1", "execute", "franchise_db", "--remote", "--file", filePath], {
    cwd: ROOT_DIR,
    encoding: "utf8",
    maxBuffer: 20 * 1024 * 1024,
  });
  process.stdout.write(result.stdout || "");
  process.stderr.write(result.stderr || "");
  if (result.status !== 0) {
    throw new Error(`Remote D1 apply failed with status ${result.status}`);
  }
}

function stableId(...parts: string[]) {
  return createHash("sha1").update(parts.join("|")).digest("hex").slice(0, 20);
}

function sql(value: unknown) {
  if (value === null || value === undefined || value === "") return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function ensureParent(filePath: string) {
  const dirPath = dirname(filePath);
  if (!existsSync(dirPath)) {
    throw new Error(`Missing output directory: ${dirPath}`);
  }
}

main();
